export const POST = 'POST';
export const GET = 'GET';

export const SET_RESPONSE_DATA = 'SET_RESPONSE_DATA';

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

export const SET_ROUTER_STATE = 'SET_ROUTER_STATE';
export const CLEAR_ROUTER_STATE = 'CLEAR_ROUTER_STATE';

export const SET_PAGE_STATE = 'SET_PAGE_STATE';
export const CLEAR_PAGE_STATE = 'CLEAR_ROUTER_STATE';

